describe('test functionalities', () => {
  it("should display 10 cats for each click on 'view more'", () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy=cat-card]').should('have.length', 10)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 20)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 30)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 40)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 50)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 60)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 70)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 80)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 90)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=cat-card]').should('have.length', 100)
    cy.get('[data-cy=view-more-button]').click()
    cy.get('[data-cy=view-more-button]').should('not.exist')
  })
  it("should get cats for the search 'sav'", () => {
    cy.visit('http://localhost:3000/')
    cy.get('input').type('sav')
    cy.get('[data-cy=submit-search-button]').click();
    cy.get('[data-cy=cat-card]').should('exist')
  })
  it("should put the first cat in favourite and find it in favourite tab", () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy=cat-card]').first().get('[data-cy=favourite-button]').first().click()
    cy.get('[data-cy=favourite-tab]').should('have.text', 'My Favourites (1)')
    cy.get('[data-cy=favourite-tab]').click().get('[data-cy=cat-card]').should('have.length', 1)
  })
  it("should delete the first cat in favourite and don't find it in favourite tab", () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy=favourite-tab]').should('have.text', 'My Favourites (1)')
    cy.get('[data-cy=favourite-tab]').click().get('[data-cy=cat-card]').should('have.length', 1)
    cy.get('[data-cy=cat-card]').first().get('[data-cy=favourite-button]').first().click()
    cy.get('[data-cy=favourite-tab]').click().get('[data-cy=cat-card]').should('have.length', 0)
    cy.get('[data-cy=home-tab]').click().get('[data-cy=cat-card]').should('have.length', 10)
    cy.get('[data-cy=cat-card]').first().get('[data-cy=favourite-button]').first().get('span').should('have.css', 'fill', 'rgb(0, 0, 0)')
  })
  it("should update name and description of the first cat", () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-cy=cat-card]').first().get('[data-cy=update-button]').first().click()
    cy.get('[data-cy=update-name-input]').clear().type('New Name')
    cy.get('textarea').clear().type('New Description')
    cy.get('[data-cy=submit-update-button]').click();
    cy.get('[data-cy=cat-card]').first().find('[data-cy=card-cat-name]').should('have.text', 'New Name')
    cy.get('[data-cy=cat-card]').first().find('[data-cy=card-cat-description]').should('have.text', 'New Description')
  })
})